resources:
- ../../base

nameSuffix: -prod




patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

    - op: replace
      path: /spec/strategy/canary/stableService
      value: guestbook-ui-prod

    - op: replace
      path: /spec/strategy/canary/canaryService
      value: guestbook-ui-canary-prod

    - op: replace
      path: /spec/strategy/canary/trafficRouting/nginx/stableIngress
      value: guestbook-ui-ingress-prod
  target:
    kind: Rollout
    name: guestbook-ui

 # ðŸ‘‡ HOST-BASED ROUTING PATCH (PROD)
- target:
    kind: Ingress
    name: guestbook-ui-ingress
  patch: |-
    - op: add
      path: /spec/rules/0/host
      value: guestbook-prod.local
images:
- name: udemykcloud534/guestbook
  newName: udemykcloud534/guestbook
  newTag: 7aabd5f
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
