apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: guestbook=udemykcloud534/guestbook
    argocd-image-updater.argoproj.io/guestbook.update-strategy: latest
    argocd-image-updater.argoproj.io/guestbook.allow-tags: regexp:^[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/guestbook.tag-order: lexicographical
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd.argoproj.io/secret-type: repo-creds
spec:
  project: guestbook
  source:
    repoURL: https://github.com/crazylearning-cr/guestbook.git
    targetRevision: main
    path: k8s-manifests/guestbook-rollout/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
spec:
  project: guestbook
  source:
    repoURL: https://github.com/crazylearning-cr/guestbook.git
    targetRevision: main
    path: k8s-manifests/guestbook-rollout/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true