resources:
- ../../base
nameSuffix: -dev
patches:
- target:
    kind: Rollout
    name: guestbook-ui
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

    - op: replace
      path: /spec/strategy/canary/stableService
      value: guestbook-ui-dev

    - op: replace
      path: /spec/strategy/canary/canaryService
      value: guestbook-ui-canary-dev

    - op: replace
      path: /spec/strategy/canary/trafficRouting/nginx/stableIngress
      value: guestbook-ui-ingress-dev
- target:
    kind: Ingress
    name: guestbook-ui-ingress
  patch: |-
    - op: add
      path: /spec/rules/0/host
      value: guestbook-dev.34.204.31.114.nip.io
images:
- name: udemykcloud534/guestbook
  newTag: 3270caf
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
